// action types
const SET_WORKSHOPS = "SET_WORKSHOPS";
const SET_ERROR = "SET_ERROR";
const FETCH_WORKSHOPS = "FETCH_WORKSHOPS";
const PREVIOUS_PAGE = "PREVIOUS_PAGE";
const NEXT_PAGE = "NEXT_PAGE";

export {
    SET_WORKSHOPS,
    SET_ERROR,
    FETCH_WORKSHOPS,
    PREVIOUS_PAGE,
    NEXT_PAGE
};