// action types
const SET_WORKSHOPS = "SET_WORKSHOPS";
const SET_ERROR = "SET_ERROR";
const SET_COMPLETED = "SET_COMPLETED";
const PREVIOUS_PAGE = "PREVIOUS_PAGE";
const NEXT_PAGE = "NEXT_PAGE";

export {
    SET_WORKSHOPS,
    SET_ERROR,
    SET_COMPLETED,
    PREVIOUS_PAGE,
    NEXT_PAGE
};